development:
  secret_key_base: 695c0eb30ec2470898471fe34642d79a648cad4e34d5d39f95c3ca80491df2b06a65d311ddf036a7d693cb92b8519aacc494ac1c7b4f376e895d0bb891a60c19

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
